name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file  Karaoke.WebApi/Dockerfile
  
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Login no DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build docker image
      run: docker build -t chagasduarte/karaoke.webapi .
    - name: Push image Docker
      run: docker push chagasduarte/karaoke.webapi

